### ISSUE TITLE
Please add example of `~/.s3cfg` for s3cmd in `How to connect` for S3 object storage

### ISSUE THREAD

**Issue by vadimkantorov** [nebius/nebius-solutions-library#350]
The `How to connect` section explains how to successfully set up `aws-cli`

Related, but simpler `s3cmd` uses a different config format. I've tried setting it up as:

```toml
[default]
access_key = ABC...
secret_key = def...
host_base = https://storage.eu-north1.nebius.cloud:443
use_https = yes
```

This lets me do `s3cmd ls`, but does not let me do `s3cmd ls s3://mynebiusbucket`: `ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.`

---

For comparison, here is the configuration of AWS-cli:
```
$ cat ~/.aws/config
[default]
region = eu-north1
endpoint_url = https://storage.eu-north1.nebius.cloud:443

$ cat ~/.aws/credentials
[default]
aws_access_key_id = ABC...
aws_secret_access_key = def...
```
